version: '3'

services:
  ui:
    build:
      context: .
    networks:
      - simpl
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    command: /code/compose-bootstrap.sh
    environment:
      - DJANGO_SETTINGS_MODULE=simpl_blackjack_ui.settings
      - MODEL_SERVICE_WS=ws://localhost:8080/ws
      - SIMPL_GAMES_URL=http://api:8000/apis/
    stop_signal: SIGKILL

networks:
  simpl:
    external:
      name: simpl-games-api_simpl
